import os
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from app.models.blueprint import BlueprintResult


OUTPUT_DIR = "generated_blueprints"


def _ensure_output_dir():
    os.makedirs(OUTPUT_DIR, exist_ok=True)


def _add_cover_page(doc: Document, result: BlueprintResult, answers_dict: dict):
    doc.add_paragraph()
    doc.add_paragraph()
    doc.add_paragraph()

    title = doc.add_heading(result.app_name, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph("Project Blueprint")
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle.runs[0].font.size = Pt(18)
    subtitle.runs[0].font.color.rgb = RGBColor(0x44, 0x44, 0x44)

    doc.add_paragraph()

    meta = doc.add_paragraph(f"Generated by DevBlueprint AI\n{datetime.now().strftime('%B %d, %Y')}")
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta.runs[0].font.size = Pt(11)
    meta.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    stack_info = (
        f"Stack: {answers_dict.get('tech_stack_backend', '')} · "
        f"{answers_dict.get('tech_stack_frontend', '')} · "
        f"{answers_dict.get('tech_stack_database', '')}"
    )
    stack_para = doc.add_paragraph(stack_info)
    stack_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    stack_para.runs[0].font.size = Pt(10)
    stack_para.runs[0].font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    doc.add_page_break()


def _add_table_of_contents(doc: Document, result: BlueprintResult):
    doc.add_heading("Table of Contents", level=1)
    for chapter in result.chapters:
        toc_line = doc.add_paragraph(
            f"Chapter {chapter.chapter_number} — {chapter.title}",
            style="List Number"
        )
        toc_line.runs[0].font.size = Pt(11)
    doc.add_page_break()


def _add_chapter(doc: Document, chapter_number: int, title: str, content: str):
    doc.add_heading(f"Chapter {chapter_number} — {title}", level=1)
    doc.add_paragraph()

    for line in content.split("\n"):
        line = line.rstrip()

        if line.startswith("### "):
            doc.add_heading(line[4:], level=3)
        elif line.startswith("## "):
            doc.add_heading(line[3:], level=2)
        elif line.startswith("# "):
            doc.add_heading(line[2:], level=2)
        elif line.startswith("- ") or line.startswith("* "):
            doc.add_paragraph(line[2:], style="List Bullet")
        elif line.startswith("```") or line == "```":
            pass  # Skip code fence markers for MVP 1
        elif line.strip() == "":
            doc.add_paragraph()
        else:
            doc.add_paragraph(line)

    doc.add_page_break()


def build_document(result: BlueprintResult, answers_dict: dict) -> str:
    _ensure_output_dir()

    doc = Document()

    _add_cover_page(doc, result, answers_dict)
    _add_table_of_contents(doc, result)

    for chapter in result.chapters:
        _add_chapter(doc, chapter.chapter_number, chapter.title, chapter.content)

    filename = f"{result.app_name.replace(' ', '_')}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    doc.save(filepath)

    return filepath
